import FWCore.ParameterSet.Config as cms

PREMIXEventContent = cms.PSet(
    outputCommands = cms.untracked.vstring(
        'drop *', 
        'keep CrossingFramePlaybackInfoNew_*_*_*', 
        'keep PileupSummaryInfos_*_*_*', 
        'keep int6stdbitsetstdpairs_*_AffectedAPVList_*', 
        'keep int_*_bunchSpacing_*', 
        'keep *_genPUProtons_*_*', 
        'keep *_mix_MergedTrackTruth_*', 
        'keep *_randomEngineStateProducer_*_*', 
        'keep *_logErrorHarvester_*_*', 
        'keep Phase2TrackerDigiedmDetSetVector_mix_*_*', 
        'keep *_*_Phase2OTDigiSimLink_*', 
        'keep *_simSiPixelDigis_*_*', 
        'keep EBDigiCollection_simEcalDigis_*_*', 
        'keep EEDigiCollection_simEcalDigis_*_*', 
        'keep ESDigiCollection_simEcalUnsuppressedDigis_*_*', 
        'keep *_simHcalDigis_*_*', 
        'drop ESDigiCollection_simEcalUnsuppressedDigis_*_*', 
        'drop EEDigiCollection_simEcalDigis_*_*', 
        'keep *_simHGCalUnsuppressedDigis_EE_*', 
        'keep *_simHGCalUnsuppressedDigis_HEfront_*', 
        'keep *_simHGCalUnsuppressedDigis_HEback_*', 
        'keep *_mix_MergedCaloTruth_*', 
        'keep *_mix_FTLBarrel_*', 
        'keep *_mix_FTLEndcap_*', 
        'keep *_mix_InitialVertices_*', 
        'keep *_mix_FTLBarrel_*', 
        'keep *_mix_FTLEndcap_*', 
        'keep *_mix_InitialVertices_*', 
        'keep *_mix_g4SimHitsMuonDTHits_*', 
        'keep *_mix_g4SimHitsMuonCSCHits_*', 
        'keep *_mix_g4SimHitsMuonRPCHits_*', 
        'keep *_mix_g4SimHitsMuonGEMHits_*', 
        'keep *_mix_g4SimHitsMuonME0Hits_*'
    ),
    splitLevel = cms.untracked.int32(0)
)